# Generated by Django 5.0.3 on 2024-03-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='Задача',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='Приоритет',
            field=models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], default='Низкий', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='Статус',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('Отменено', 'Отменено'), ('Отложено', 'Отложено')], default='Выполнено', max_length=20),
        ),
    ]
